// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHobvLT9eZ9IA7b_fKiCIzHlSTw6u73So',
    appId: '1:966640225954:web:321a2c8a6d49f0ced451fb',
    messagingSenderId: '966640225954',
    projectId: 'instagram-3c057',
    authDomain: 'instagram-3c057.firebaseapp.com',
    storageBucket: 'instagram-3c057.firebasestorage.app',
    measurementId: 'G-VLRDSJ8PVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBANwqCYWUDdwzzUAFRBr7hGsR5bYIHGk',
    appId: '1:966640225954:android:a6a7bc53c331ee30d451fb',
    messagingSenderId: '966640225954',
    projectId: 'instagram-3c057',
    storageBucket: 'instagram-3c057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSN0xsnIhHUz0rFJQur9Uq2ralcg4nXo',
    appId: '1:966640225954:ios:4c9c380d366409efd451fb',
    messagingSenderId: '966640225954',
    projectId: 'instagram-3c057',
    storageBucket: 'instagram-3c057.firebasestorage.app',
    iosBundleId: 'com.example.instagramSeries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHobvLT9eZ9IA7b_fKiCIzHlSTw6u73So',
    appId: '1:966640225954:web:b3df7369d6761d34d451fb',
    messagingSenderId: '966640225954',
    projectId: 'instagram-3c057',
    authDomain: 'instagram-3c057.firebaseapp.com',
    storageBucket: 'instagram-3c057.firebasestorage.app',
    measurementId: 'G-NDDN02Q7CN',
  );

}