name: instagram_series
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^2.0.2

  # UI packages
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  fluttertoast: ^8.0.9
  google_sign_in: ^6.3.0
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Update to the latest version

flutter:
  uses-material-design: true

  assets:
    - assets/images/
